export const LOAD_RESOURCE_DATA_START = 'LOAD_RESOURCE_DATA_START';
export const LOAD_RESOURCE_DATA_SUCCESS = 'LOAD_RESOURCE_DATA_SUCCESS';
export const LOAD_RESOURCE_DATA_FAILURE = 'LOAD_RESOURCE_DATA_FAILURE';