export const LOAD_RESOURCE_DATA_START = 'LOAD_RESOURCE_DATA_START';
export const LOAD_RESOURCE_DATA_SUCCESS = 'LOAD_RESOURCE_DATA_SUCCESS';
export const LOAD_RESOURCE_DATA_FAILURE = 'LOAD_RESOURCE_DATA_FAILURE';

export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';

export const FILTER_RESOURCE_BY_CATEGORIES = 'FILTER_RESOURCE_BY_CATEGORIES';

export const ADD_SAVED_RESOURCE = 'ADD_SAVED_RESOURCE';

export const REMOVE_SAVED_RESOURCE = 'REMOVE_SAVED_RESOURCE';

export const GROUP_RESOURCE_BY_COORDINATES_START = 'GROUP_RESOURCE_BY_COORDINATES_START';
export const GROUP_RESOURCE_BY_COORDINATES_SUCCESS = 'GROUP_RESOURCE_BY_COORDINATES_SUCCESS';