export const LOAD_RESOURCE_DATA_START = 'LOAD_RESOURCE_DATA_START';
export const LOAD_RESOURCE_DATA_SUCCESS = 'LOAD_RESOURCE_DATA_SUCCESS';
export const LOAD_RESOURCE_DATA_FAILURE = 'LOAD_RESOURCE_DATA_FAILURE';

export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';

export const LOAD_CATEGORY_GROUPS = 'LOAD_CATEGORY_GROUPS';

export const FILTER_RESOURCE_BY_CATEGORIES = 'FILTER_RESOURCE_BY_CATEGORIES';

export const FILTER_CATEGORIES_BY_GROUP = 'FILTER_CATEGORIES_BY_GROUP';

export const FILTER_RESOURCE_BY_SEARCH = 'FILTER_RESOURCE_BY_SEARCH';

export const ADD_SAVED_RESOURCE = 'ADD_SAVED_RESOURCE';

export const REMOVE_SAVED_RESOURCE = 'REMOVE_SAVED_RESOURCE';