export const LOAD_RESOURCE_DATA_START = 'LOAD_RESOURCE_DATA_START';
export const LOAD_RESOURCE_DATA_SUCCESS = 'LOAD_RESOURCE_DATA_SUCCESS';
export const LOAD_RESOURCE_DATA_FAILURE = 'LOAD_RESOURCE_DATA_FAILURE';

export const LOAD_CATEGORIES_START = 'LOAD_CATEGORIES_START';
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
export const LOAD_CATEGORIES_FAILURE = 'LOAD_CATEGORIES_FAILURE';